### PR TITLE
Update AWS SDK to v1.1.29

### PR DESCRIPTION
**Pull request by variadico**
This updates the vendored AWS SDK to ~~v1.1.28~~ v1.1.29.

@lilirui @y0ssar1an @zquestz

### CODE REVIEW

**Comment by lilirui** [comment]
v1.1.29 is just out :)

**Comment by zquestz** [comment]
LOL figures. =)

**Comment by variadico** [comment]
Okay. Updated to latest.

**Comment by lilirui** [comment]
LGTM

**Pull request merged**
