### PR TITLE
Extend SSH timeout for AWS to 10 minutes.

### PR DESCRIPTION
**Pull request by zquestz**
Seeing periodic SSH timeouts when booting several VMs at the same time on AWS. This just extends the timeout from 5 to 10 minutes.

@lilirui @variadico @tw4dl

### CODE REVIEW

**Comment by variadico** [comment]
Seems fine. 10 minutes will be worst case and failed connects will be retried with a 5-second sleep in between.

LGTM

**Comment by lilirui** [comment]
I would suggest exposing the timeout so it can be overwritten by application.

**Comment by variadico** [comment]
Wait. I kinda like that idea.

```
var SSHTimeout
```

instead of `const`.

That way people can say `aws. SSHTimeout = 10 * time.Minutes` or whatever they please.

**Comment by zquestz** [comment]
@variadico feel free to make that change. I like it too. Just amend this PR. I am digging into something else. =)

**Comment by zquestz** [comment]
I like, we should also put in an issue to do this for other providers, as I think this is very useful. For now though - LGTM!

**Comment by lilirui** [comment]
LGTM

**Comment by zquestz** [comment]
We can close this since all SSHTimeouts are now exposed in the other PR.

**Pull request closed without merging**
